# NUMPY
### NumPy — библиотека с открытым исходным кодом для языка программирования Python. Возможности numpy:

### поддержка многомерных массивов (включая матрицы); поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

<img src="../../numpy.PNG">

Основной структурной единицей NUMPY является массив, то есть объект класса numpy.array

Разберемся, как создаются массивы

In [2]:
#Прежде всего - импортируем numpy
import numpy as np

#Создание массива 
#Создание из листа

A = [1,2,3]
A*2

[1, 2, 3, 1, 2, 3]

In [2]:
#Создание копированием другого массива
B = A.copy()
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Существует возможность построения диапазона чисел от From (включая) до To (не включая) с шагом Step:

From = 2.5
To = 7
Step = 0.5
A = np.arange(From, To, Step)
A

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [5]:
"""Специальные функции создания массивов"""
#Функция создания массива определенной формы, заполненного константами
A = np.full((5,6), 4.5)
A

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [6]:
#Создание пусстого массива указанной формы
B = np.empty((5,6))
B

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [9]:
# Создание единичнодиагонального  квадратного массива
C = np.identity(5)
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#Создание нулевого/единичного массива с заданными размерами
A = np.zeros((2, 3, 2))
B = np.ones((3,2))
C = np.eye(5)

In [10]:
A

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Векторные операции

In [11]:
''' 
Как сделать поэлементное сложение двух списков python?
Задача не решается при помощи простых синтаксических конструкций: 
Если прописать оператор сложения, мы получим **конкатенацию**
'''

A = [1,2,3,4]
B = [5,6,7,8, 9]

A + B

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
"""
Это логично, когда мы говорим о массивах, как о хранилище данных, имеющих произвольный тип
Но если мы говорим о числовых векторах, логично переопределить оператор сложения. Именно это и сделано в Numpy
"""

A = np.array([[-1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = np.array([[1., -2., -3.], [7., 8., 9.], [4., 5., 6.]])
A

array([[-1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [15]:
B

array([[ 1., -2., -3.],
       [ 7.,  8.,  9.],
       [ 4.,  5.,  6.]])

In [16]:
A + B

array([[ 0.,  0.,  0.],
       [11., 13., 15.],
       [11., 13., 15.]])

In [17]:
"""
Вычитание также доступно
"""
A - B

array([[-2.,  4.,  6.],
       [-3., -3., -3.],
       [ 3.,  3.,  3.]])

In [19]:
"""
Да и вообще все арифметические действия вплоть до возведения в степень
"""
A = np.ones((3,3))
B = np.full_like(A, 4)   #<- Обратите внимание на like-функцию

In [20]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [22]:
A*B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [23]:
A/B

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

In [24]:
A**B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
B**A

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [26]:
"""
Все те же операции доступны и в случае, когда один из аргументов - константа
"""

A = np.array([[-1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = -2.
A

array([[-1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [27]:
A + B

array([[-3.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [28]:
A - B

array([[ 1.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [29]:
A*B

array([[  2.,  -4.,  -6.],
       [ -8., -10., -12.],
       [-14., -16., -18.]])

In [30]:
A/B

array([[ 0.5, -1. , -1.5],
       [-2. , -2.5, -3. ],
       [-3.5, -4. , -4.5]])

In [31]:
A**B

array([[1.        , 0.25      , 0.11111111],
       [0.0625    , 0.04      , 0.02777778],
       [0.02040816, 0.015625  , 0.01234568]])

In [32]:
B**A

array([[-5.00e-01,  4.00e+00, -8.00e+00],
       [ 1.60e+01, -3.20e+01,  6.40e+01],
       [-1.28e+02,  2.56e+02, -5.12e+02]])

In [42]:
"""
Оказывается, похожие вещи можно делать и тогда, когда аргументы A и B - массивы разных размерностей
В этом случае numpy постарается выделить из массива A подэлементы размерности, 
схожей с B и провести нужную операцию поэлементно с этими пподэлементами

Такая операция называется broadcast
"""

A = np.ones((3,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [44]:
A - B

array([[ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.],
       [ 1.,  0., -1., -2., -3.]])

In [45]:
A*B

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [46]:
A/B

C:\Users\dboy\AppData\Local\Temp\ipykernel_18988\713994841.py:1: RuntimeWarning: divide by zero encountered in divide
  A/B


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ]])

In [49]:
np.isinf(A/B).any()

C:\Users\dboy\AppData\Local\Temp\ipykernel_18988\3223077836.py:1: RuntimeWarning: divide by zero encountered in divide
  np.isinf(A/B).any()


True

In [50]:
"""
А что, если не получается совместить размерности A и B?
Например:
"""

A = np.ones((3,3))
B = np.zeros((2,4))

In [51]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
"""
В этом случае мы получаем ValueError: operands could not be broadcast together
"""
A*B

ValueError: operands could not be broadcast together with shapes (3,3) (2,4) 

In [53]:
A + B

ValueError: operands could not be broadcast together with shapes (3,3) (2,4) 

# Работа с массивами, как с элементами векторного пространства

In [61]:
"""
Все одномерные массивы могут быть представлены нами, как элементы многомерного линейного пространства
А двумерные - как элементы пространства матриц определенного размера

Эти случаи представляют для нас особую значимость, поскольку тут мы можем применить методы линейной алгебры
"""

from numpy import linalg as linalg

In [62]:
"""
Рассмотрим прежде всего операции над матрицами:


-Произведение матриц
-Возведение в степень
"""

A = np.ones((4,3))
B = np.full((3,5), 3)

In [63]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
B

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [65]:
"""
перемножение матриц можно осуществить при помощи одной из двух функций:
np.dot
np.matmul
"""

np.matmul(A,B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [66]:
np.dot(A,B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [67]:
A@B

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [68]:
"""
Возведение матрицы в степень происходит при помощи linalg.matrix_power
"""
A = np.ones((3,3))
linalg.matrix_power(A,2)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [57]:
linalg.matrix_power(A,3)

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [69]:
"""
Характеристики матриц и векторов:

-Норма
-Айгенпары
-Определители
"""

A = np.ones(5)

In [70]:
A

array([1., 1., 1., 1., 1.])

In [71]:
linalg.norm(A)

2.23606797749979

In [72]:
np.sqrt(5)

2.23606797749979

In [75]:
"""
Собственные числа и собственные векторы
"""
A = np.array([[-1, -6], [2,6]])
A

array([[-1, -6],
       [ 2,  6]])

In [76]:
linalg.eig(A)

EigResult(eigenvalues=array([2., 3.]), eigenvectors=array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]]))

In [77]:
"""
При помощи numpy можно также решать системы линейных уравнений, заданных в виде Ax = b
"""

A = np.array([[1, 2], [3, 1]])
b = np.array([5, 0])

In [78]:
A

array([[1, 2],
       [3, 1]])

In [79]:
b

array([5, 0])

In [80]:
linalg.solve(A, b)

array([-1.,  3.])

In [81]:
"""
Определители
"""

A = np.array([[1, 3],[2, 6]])
A

array([[1, 3],
       [2, 6]])

In [69]:
linalg.det(A)

0.0

In [70]:
A = np.array([[4, 3],[2, 6]])
A

array([[4, 3],
       [2, 6]])

In [71]:
linalg.det(A)

17.999999999999996