# Задачи:
## 1 Опишите своими словами как выглядит одномерный двумерный массив?
## 2 Что произойдёт с этим массивом,если добавится третья ось?
## 3 Какие вычисления способна производить NumPy с этими данными?
## 4 Пусть дан массив: 
e =np.array([(1,2,3),(4,5,6)]).
Реализуйте в NumPy простейший срез по рядам

In [6]:
"""
"Мерность" массивов определяется кол-вом "осей", одномерный - по оси х (линейный, строка), 
двумерный по осям х-у (строка, столбец), трех мерный х-у-z (строка, столбец, глубина)
"""
import numpy as np
e =np.array([(1,2,3),(4,5,6)])
e


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
""" Срез по первой строке (0)"""
e[0]

array([1, 2, 3])

In [8]:
""" Срез по второй строке (1)"""
e[1]

array([4, 5, 6])

Задачи:
1	Какие функции выполняет модуль Random?
2	Как создать массив с помошью модуля?
3	Назовите способ сделать случайную выборку из массива?
4	Что вообше такое - случайные числа?

In [9]:
"""
1 Модуль random — это модуль, который позволяет генерировать псевдослучайные числа и таким образом имитировать случайные события
2 import numpy as np        
  from numpy import random
  random.rand()  "Генерируем случайное число от 0 до 1."
3 Воспользуемся методом choice. "random.choice([х, х, ..., х, х])""
4 "Случайная величина. Случайная величина (random variable) — это величина, которая в зависимости от случая может принимать определенное значение с заданной вероятностью"

"""

'\n1 Модуль random — это модуль, который позволяет генерировать псевдослучайные числа и таким образом имитировать случайные события\n2 import numpy as np        \n  from numpy import random\n  random.rand()  "Генерируем случайное число от 0 до 1."\n3 Воспользуемся методом choice. "random.choice([х, х, ..., х, х])""\n4 "Случайная величина. Случайная величина (random variable) — это величина, которая в зависимости от случая может принимать определенное значение с заданной вероятностью"\n\n'